# Generated by Django 4.1.1 on 2022-09-11 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.CharField(default='', max_length=5)),
                ('subject_name', models.CharField(default='', max_length=64)),
                ('section', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='subject',
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='course_number',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='booking.subject'),
        ),
    ]
