# Generated by Django 4.1.1 on 2022-09-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_subject_remove_booking_subject_booking_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('booking', models.ManyToManyField(blank=True, related_name='student', to='booking.booking')),
            ],
        ),
    ]
