# Generated by Django 4.1.1 on 2022-09-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='booking',
            field=models.ManyToManyField(blank=True, default='', to='booking.booking'),
        ),
    ]
