# Generated by Django 4.1.1 on 2022-10-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_subject_seats_subject_semester_subject_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='capacity',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='subject',
            name='seats',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
