# Generated by Django 4.1.1 on 2022-10-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_subject_capacity_alter_subject_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='seats',
            field=models.IntegerField(null=True),
        ),
    ]
