# Generated by Django 4.1.1 on 2022-10-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_subject_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='capacity',
        ),
        migrations.AlterField(
            model_name='subject',
            name='seats',
            field=models.CharField(default='', max_length=10),
        ),
    ]
