# Generated by Django 4.1.1 on 2022-10-05 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0008_remove_subject_capacity_alter_subject_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='seats',
        ),
        migrations.AddField(
            model_name='subject',
            name='seats',
            field=models.ManyToManyField(blank=True, related_name='subjects', to=settings.AUTH_USER_MODEL),
        ),
    ]
